### ISSUE TITLE
Consider releasing on PyPI?

### ISSUE THREAD

**Issue by sgherbst** [StanfordVLSI/JusTAG#2]
I think it would be awesome if JusTAG could be installed from PyPI with something like ``pip install justag``. 

If this interests you, there are a couple of sub-tasks:
1. Move folders outside of ``justag`` (like ``rtl`` and ``verif``) into ``justag``, since that is the folder that will be installed by pip.
2. There are various options to include non-Python files in the source distribution (e.g., ``*.svp`` files), but I tend to use a top-level file called ``MANIFEST.in`` like this example from **anasymod**:
https://github.com/sgherbst/anasymod/blob/bbaa0c60f0c0657f6b105f62ae0f09b6f1a22dd4/MANIFEST.in#L1-L2
3. To make ``JustTAG.py`` available as a script that can be called directly by the user (i.e., ``JustTAG`` instead of ``python $JUSTAG_DIR/JustTAG.py``), you can use ``entry_points`` in ``setup.py`` like this example from **anasymod**:
https://github.com/sgherbst/anasymod/blob/bbaa0c60f0c0657f6b105f62ae0f09b6f1a22dd4/setup.py#L24-L28
4. To release the package, create an account on [PyPI](https://pypi.org) and then run these commands in the top level of the repo (the first command only needs to be run once, and the last command will prompt for your PyPI credentials).  Note that each release must have a unique version number, which you can achieve by bumping the version number in ``setup.py``
```shell
> pip install twine
> python setup.py sdist
> twine upload dist/*
```
5. If you want to integrate PyPI releases with continuous integration tools, you can use GitHub actions like this example from msdsl: https://github.com/sgherbst/msdsl/blob/master/.github/workflows/release.yml.  The idea is that you store your PyPI credentials in GitHub secrets for use in the release script that is triggered by git tags starting with "v" (please be sure to use a password that isn't used elsewhere, just in case...).  Then you can release packages like this:
```shell
# first change setup.py to version 0.1.2
> git commit -am "release 0.1.2"
> git tag v0.1.2
> git push origin v0.1.2
> git push origin master
```
6. For a pretty minimal example that illustrates all of these items (except MANIFEST.in), you could take a look at my elevation data project [pyhigh](https://github.com/sgherbst/pyhigh)

**Comment by zamyers** [comment]
This should now be supported.
